#!/bin/bash

# Get .c files in tests directory
FILES=()
for f in tests/*.c; do
    FILES+=("$(basename "$f" ".c")" "")
done

# Check if any files exist
if [ ${#FILES[@]} -eq 0 ]; then
  whiptail --msgbox "No files found." 10 40
  exit 1
fi

# Show menu
CHOICE=$(whiptail \
  --title "Select a file to execute" \
  --menu "Choose:" 20 60 10 \
  "${FILES[@]}" \
  3>&1 1>&2 2>&3)

if [ $? -ne 0 ]; then
  exit 0
fi

MODE=$(whiptail \
  --title "Run mode" \
  --menu "Select execution mode:" 15 50 2 \
  normal "./miniRT" \
  debug  "gdb ./miniRT" \
  3>&1 1>&2 2>&3)

if [ $? -ne 0 ]; then
  exit 0
fi

rm -rf ./miniRT && make MAIN_FILE="tests/$CHOICE.c"

if [ "$MODE" = "debug" ]; then
  gdb --tui ./miniRT
else
  ./miniRT
fi
